security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    users_in_database:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: users_in_database
      user_checker: App\Security\UserChecker

      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        success_handler: App\Security\CustomAuthenticationSuccessHandler

      logout:
        path: app_logout

      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800
        path: /

  access_control:
    - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_JURY] }
    - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/order-card, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/track-card, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/view-card, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/tickets, roles: ROLE_USER }
